# Problem 1: Analysis of Point Patterns

## a)

```{r}
cells_data <- ppinit("../data/cells.dat")
red_data <- ppinit("../data/redwood.dat")
pines_data <- ppinit("../data/pines.dat")
```

lets test this! \todo{Hallo, Erik! Se så mye gøy vi kan gjøre med disse :D :D :D}

\begin{equation}
\bm{\mu} \neq \bm{\Sigma} + \bm{x} - x
\end{equation}

```{r}


plotProcess(cells_data, "cells")
plotProcess(red_data, "redwood")
plotProcess(pines_data, "pines")

```


## b)

```{r}

cells_L <- Kfn(cells_data, 1)
red_L <- Kfn(red_data, 1)
pines_L <- Kfn(pines_data, 1)

plotLFunc(cells_L, "cells")
plotLFunc(red_L, "redwood")
plotLFunc(pines_L, "pines")
```


## c)

```{r}
testIfPois(data = cells_data, 
           simulatePois = simulateHomoPois, 
           args = list(n = length(cells_data$x), area = cells_data$area),
           title = "cells")

testIfPois(red_data, 
           simulatePois = simulateHomoPois, 
           args = list(n = length(red_data$x), area = red_data$area),
           title = "redwood" )

testIfPois(pines_data,
           simulatePois = simulateHomoPois, 
           args = list(n = length(pines_data$x), area = pines_data$area),
           title = "pines")


```
