# Problem 4: Repulsive event spatial variables

## a)

(ref:repulsive) Empirical $\mathbf{L}$-function for the biological cell data along with empirical 0.9-confidence intervals for the $\mathbf{L}$-function. Thes are made from simulation of 100 Strauss event RF models with parameters AHAHJASHDSDHF.
\todo{fill out figure caption}

```{r repulsive, fig.cap = "(ref:repulsive)"}

# evaluation of MCMC algorithm

  phi_0 <- 100
  phi_1 <- 50
  tau_0 <- 0.02
  k <- length(cells_data$x)
  num_iter <- 2000
  area <- cells_data$area
  jumps <- 10
  
  
  
  args <- list(phi_0 = phi_0,
               phi_1 = phi_1,
               tau_0 = tau_0,
               k = k,
               area = area,
               acceptanceFunc = acceptanceRepulsive,
               num_iter = num_iter,
               jumps = jumps)
  
  
  gg <- testIfPois(data = cells_data,
           simulatePois = generateRepulsivePois,
           args = args,
           num_real = 100)
  
  data <- generateRepulsivePois(args)
  
  plotProcess(data)
  
  
  num_test <- 10
  gg_1 <- testBurnIn(evalFunc = evaluateMeanMinDist,
                     args = args,
                     num_test = num_test,
                     title = "Mean min distance")
  
  gg_2 <- testBurnIn(evalFunc = evaluateMeanMaxDist,
                     args = args,
                     num_test = num_test,
                     title = "Mean max distance")
  
  gg_3 <- testBurnIn(evalFunc = evaluateMaxDist,
                     args = args,
                     num_test = num_test,
                     title = "Max distance")
  
  gg_4 <- testBurnIn(evalFunc = evaluateMinDist,
                     args = args,
                     num_test = num_test,
                     title = "Min distance")
  
  grid.arrange(gg_1, gg_2, gg_3, gg_4)
  
  
  

  
  # doMCMC <- function(acceptanceFunc, num_iter, jumps, args, events_mat){


```



```{r}

testIfPois(data = cells_data,
           simulatePois = generateRepulsivePois,
           args = args,
           num_real = 100)

```
